# Problem 44
# Pentagon Numbers
# Pentagonal numbers are generated by the formula, Pn = n(3n - 1) / 2. The first ten pentagonal numbers are: 
# 1, 5, 12, 22, 35, 51, 70, 92, 117, 145, ...
# It can be seen that P4 + P7 = 22 + 70 = 92 = P8. However, their difference, 70 - 22 = 48, is not pentagonal.
# Find the pair of pentagonal numbers, Pj and Pk, for which their sum and difference are pentagonal and D = |Pk - Pj| is minimised; what is the value of D?

from itertools import combinations

def checkPentagonal(number):
    return ((1 + (1 + 24 * number) ** 0.5) / 6).is_integer()

pentagonals = list(map(lambda n: int(n * (3 * n - 1) / 2), range(1, 10000)))

answer = 1000000000000

for combo in combinations(pentagonals, 2):
    if checkPentagonal(sum(combo)) and checkPentagonal(combo[1] - combo[0]):
        answer = min(answer, combo[1] - combo[0])

print(answer)

# 5482660