# Problem 45
# Triangular, Pentagonal, and Hexagonal
# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
# Triangle    Tn = n(n + 1)/2    1, 3, 6, 10, 15, ...
# Pentagonal    Pn = n(3n - 1)/2    1, 5, 12, 22, 35, ...
# Hexagonal    Hn = n(2n - 1)    1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.
# Find the next triangle number that is also pentagonal and hexagonal.

def checkPentagonal(number):
    return ((1 + (1 + 24 * number) ** 0.5) / 6).is_integer()

def checkTriangle(number):
    return (((1 + 8 * number) ** 0.5 - 1) / 2).is_integer()

i = 41328
gap = 573

while True:
    if checkPentagonal(i) and checkTriangle(i):
        answer = i
        break
    gap += 4
    i += gap

print(answer)

# 1533776805